
language: cpp

os: linux
dist: trusty
compiler: gcc
services: docker

env:
  global:
    - DOCKER_OPTS="--rm -ti -v ${TRAVIS_BUILD_DIR}:/build -w /build"
  matrix:
    # Python 2.7
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:python2
      BUILD_SCRIPT="python2.build"
    # Python 3
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:python3
      BUILD_SCRIPT="python3.build"
    # Java
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:java
      BUILD_SCRIPT="java.build"
    # C#
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:csharp
      BUILD_SCRIPT="csharp.build"
    # R
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:r
      BUILD_SCRIPT="r.build"
    # Scala
    - DOCKER_IMAGE=lballabio/quantlib-swig-devenv:scala
      BUILD_SCRIPT="scala.build"

before_install:
  - docker pull ${DOCKER_IMAGE}

script:
  - travis_wait 30 sleep infinity & docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./.travis/${BUILD_SCRIPT}

